name: Automatic_Sphinx_Documentation

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Setup python
    - uses: actions/setup-python@v2
    # clone the repo
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: './sphinx_docs'
        target_path: './docs'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
